name: Docker CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
  run: docker build -t milk-app ./milk_delivery_app
    - name: Run container
      run: docker run -d -p 3000:3000 milk-app
